### PR TITLE
Added support for recipients field

### PR DESCRIPTION
**Pull request by Jurisak**
I tried to add support for recipients field but unfortunately I don't know how to test it. Recipients field contains python list and I don't know how it will be consumed on the other side.

### CODE REVIEW

**Comment by ralphbean** [comment]
Thanks @Jurisak!

@mprahl, if you have free time this sprint, could you take a look at this?

**Comment by mprahl** [comment]
@Jurisak thanks for the PR. I'll merge this and then address some of the tests.

**Comment by mprahl** [comment]
@Jurisak can you link me to details on the recipients field? I don't see it in the API docs at [apiary](http://docs.resultsdb20.apiary.io). After testing it, it seems to have no effect on ResultsDB itself but perhaps we are running an older version internally that doesn't do anything with it.

**Comment by ralphbean** [comment]
I'm almost positive that resultsdb has no recipients field of its own.

If @Jurisak wants to store it, perhaps the extra data field is the right place.

**Comment by Jurisak** [comment]
Yes, resultsdb does not have any recipients field. 
Will you add an extra data field into resultsdb? 
@ralphbean or @mprahl?

**Comment by ralphbean** [comment]
No - the place to store this is in the `data` field, which already exists:  http://docs.resultsdb20.apiary.io/#reference/0/results

**Pull request merged**
