### PR TITLE
Wait for Travis CI results before building an image

### PR DESCRIPTION
**Pull request by csomh**
This will check Travis CI API a few times to find the build for the
corresponding commit and wait for it to finish, before building
a container image from the code.

### CODE REVIEW

**Comment by csomh** [comment]
> why not just run everything in Jenkins to streamline?

Was considering this, but for now this felt like the faster way to go... although I just realized that with tox in place, it shouldn't be that difficult to replicate the tests Travis is doing in Jenkins. Should I rather do the later?

**Comment by ralphbean** [comment]
Let's let @mprahl decide, since I think he was the one to setup travis originally.

**Comment by mprahl** [comment]
@csomh I have no opinion on whether to use Jenkins or TravisCI. I like TravisCI due to how little setup is needed, but if we're introducing Jenkins jobs that depend on TravisCI results, it may make sense to migrate everything to Jenkins as long as it's easy for you to configure Jenkins to post status updates to PRs.

I'll leave this up to you.

**Comment by csomh** [comment]
@mprahl posting status updates is possible but currently not easy for me. Let's merge this and revisit the topic later. Thanks!

**Pull request merged**
