### PR TITLE
Job name support in resultdb

### PR DESCRIPTION
**Pull request by Jurisak**
This field is required for future resultdb querying.

### CODE REVIEW

**Comment by mprahl** [comment]
@Jurisak what's the thought process on `job_names` vs. `job_name`? I'd much prefer to have the singular version.

**Comment by Jurisak** [comment]
@mprahl Me as well but I heard that there could be multiple job names not just single one. That's why you have this `test_name = msg['body']['msg']['job_names']` in your code.

**Comment by danc86** [comment]
It would be really handy if resultsdb-updater had some test cases showing the messages going in and the corresponding records it is inserting into resultsdb... I think that would help me to understand what exactly is happening here. Because from my (very limited!) understand it does not look right... the `job_name` is already embedded in the test case name so it seems unnecessary?

**Comment by Jurisak** [comment]
@danc86 I'll create some tests. 
I want to query resultsdb by job name and if it is in testcase name I cannot. Because it's concatenated with team name.

**Comment by ralphbean** [comment]
Ah, maybe `jenkins_job_name` would be a better field for it, to disambiguate between the testcase name (in resultsdb terms) and the job name (in jenkins terms).

**Comment by Jurisak** [comment]
@ralphbean The bad thing is that job_name can also contain non jenkins job names AFAIK.

**Comment by mprahl** [comment]
@Jurisak then if it could be multiple job names in the future, shouldn't this need to be a list then?

**Comment by Jurisak** [comment]
@mprahl @ralphbean guys you should change creation of testcase name ... because right now you are expecting that ci-message is sending only single job_names and not multiple ones ...

**Comment by mprahl** [comment]
@Jurisak you may be right. I originally thought it was a typo (the extra "s"). Can you file an issue please?

**Pull request merged**
