### PR TITLE
job_names switched to job_name field

### LINKED ISSUE #25: CI-message can contain multiple data in job_names field
Testcases are now created from job_names field but it expects that there will be only single value.
This expectation is wrong because job_names can contain multiple values divided by comma. 

Therefore creation of testcases should be fixed.

### PR DESCRIPTION
**Pull request by Jurisak**
Fixes #25

### CODE REVIEW

**Comment by Jurisak** [comment]
@ralphbean @mprahl. I am asking for code review.

**Comment by ralphbean** [comment]
Hm, we've got to be able to handle the old format at the same time (for a cutover period).

**Comment by ralphbean** [comment]
See added commit 96b4cb3c404d9ce855318dc21e2c372cfe874b28 in #28.

**Comment by Jurisak** [comment]
OK, Thank you guys. Please let me know when this commit will be in production.

**Pull request merged**
