### PR TITLE
ci_umb: we need to distinguish between scratch builds

### PR DESCRIPTION
**Pull request by thrix**
So we can simply differentiate them with Greenwave.

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by mprahl** [comment]
@thrix I'm not that familiar with Greenwave but since we are already storing whether or not it's a scratch build in the `data` dictionary of the result, could Greenwave filter off of that?

**Comment by thrix** [comment]
meh, I need to fix the tests :)

**Comment by thrix** [comment]
@mprahl sure, that were my thoughts also, but @ralphbean suggested this in RHELPLAN-6373

**Comment by thrix** [comment]
@mprahl also note we did something similar for the ci-metricsdata format, so the idea does not seem to be new. Anyway, I am fine with changing however you wish :)

**Comment by thrix** [comment]
@mprahl @ralphbean do we need something else here guys? Should we take another approach? This issue is a bit unpleasant in regards to gating (we can gate on scratch builds, as the bot cannot distinguish scratch and non-scratch)

**Comment by mprahl** [comment]
@thrix when do you need a deployment of this change?

**Comment by thrix** [comment]
@mprahl ideally ASAP, as this issue has a possible, quite unfortunate, side-effect to the gating (package gated on scratch build result). I already saw it really happen, so it is not so uncommon corner case :/

**Pull request merged**
