### PR TITLE
TPS renamed to CIPS

### PR DESCRIPTION
**Pull request by gsr-shanks**
TPS.next project has been renamed to CIPS. 
This PR addresses the change in name.

### CODE REVIEW

**Comment by gsr-shanks** [comment]
Hi,

I couldn't find an option to squash in github. All I could find as https://help.github.com/articles/about-pull-request-merges/ which states that squashing is done during merge. Could you please point me to the doc which explains how to squash while creating a new pull request ?

**Comment by csomh** [comment]
Hi @gsr-shanks,

I think what @mprahl was asking is have this change in a single git commit (as logically belongs to). For this you have to squash your commits using git and force push the new history to your fork (github has no feature to do this, as far as I know). This will update the commits that show up in this PR.

You can do the above as follows:

```bash
git checkout master
git rebase --interactive 649adb7
```

The list of commits you should see at this point in your editor will be the 7 commits you have currently, the earliest commit listed at the top. You can change `pick` to `squash` in every line, except the first, save and close the editor. This will tell git to squash all the commits into the first one and create a new commit.

Once this is done you can `git push --force` the changes to your fork. This PR should update automatically with the new list of commits (which will be 1 at this point).

If not sure about how this feature works, you can read more about rewriting history [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), especially the _Squashing Commits_ chapter.

**Comment by mprahl** [comment]
@gsr-shanks also make sure that the one leftover commit has your GitHub user as the git author.

**Comment by gsr-shanks** [comment]
Ok. Closing this one.

**Comment by gsr-shanks** [comment]
I have squashed and updated this PR. @csomh, thanks for the help.

**Comment by danc86** [comment]
Are there any backwards compatibility concerns here? Like, should it possibly look for both TPS and CIPS message names during some transition period?

Or is everything already renamed to CIPS?

**Comment by gsr-shanks** [comment]
No transition period. Thanks.

**Comment by danc86** [comment]
In that case :+1: it makes sense to me... but let's get a review from a proper expert like @mprahl :-)

**Comment by mprahl** [comment]
LGTM

**Pull request merged**
