### PR TITLE
Scratch build support

### PR DESCRIPTION
**Pull request by Jurisak**
+ brew_task_id which is unique scratch build identificator
+ test artifact
+ modified test_type value if build_type is scratch

### CODE REVIEW

**Comment by mprahl** [comment]
LGTM. I assume the tests will need tweaking. I'm not sure why they're passing since the POST values will have changed, but I can handle that after merging.

@ralphbean are you good with this change?

**Comment by ralphbean** [comment]
> are you good with this change?

Sorry, I'm sacked today and can't review.  Can you respond on the pnt-factory2-devel thread about this and see if anyone else there can contribute further review?

**Comment by Jurisak** [comment]
@mprahl @ralphbean Guys, how do you see this PR?

**Comment by ralphbean** [comment]
> @ralphbean are you good with this change?

Yeah @mprahl, I'm :+1:.

**Comment by ralphbean** [comment]
@Jurisak, sorry for the delay.  Merging!

**Pull request merged**
