### PR TITLE
Add support for redhat-container-image type

### PR DESCRIPTION
**Pull request by hluk**
JIRA: FACTORY-5235
Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by hluk** [comment]
PR for the message schema: https://pagure.io/fedora-ci/messages/pull-request/89

**Comment by thrix** [comment]
@hluk if changes go through in the pagure PR, the exaples will need an edit

**Comment by hluk** [comment]
This is still blocked by https://pagure.io/fedora-ci/messages/pull-request/89.

cc @lcarva

**Comment by hluk** [comment]
@gnaponie, @lcarva I think we can merge this now and fix it later if anything changes in new not-yet-completed message schema (https://pagure.io/fedora-ci/messages/pull-request/89). Otherwise, this will be blocked at least until 15th January.

What do you think?

**Comment by lcarva** [comment]
> @gnaponie, @lcarva I think we can merge this now and fix it later if anything changes in new not-yet-completed message schema (https://pagure.io/fedora-ci/messages/pull-request/89). Otherwise, this will be blocked at least until 15th January.
> 
> What do you think?

I'm happy with having this in an early preview state.

**Comment by gnaponie** [comment]
Agreed! I'm ok with merging this.

**Pull request merged**
