### PR TITLE
Add optional scenario data field

### PR DESCRIPTION
**Pull request by hluk**
New scenario message attribute: https://pagure.io/fedora-ci/messages/pull-request/103

JIRA: RHELWF-804
Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by pkotvan** [comment]
Hi @hluk, I'd like to ask what is the process now to get this request merged. Thanks.

**Comment by hluk** [comment]
@pkotvan Normally, someone else reviews, we merge it and usually release it in one or two weeks, if there is no pipeline deployment freeze.

For this, I wanted to add a test case, but the `productmd-compose` message in tests uses an old schema version. I have been hoping someone can provide a new example message.

**Comment by hluk** [comment]
I've added a test with an example message.

**Comment by pkotvan** [comment]
Thank you very much for the information and for your time!

**Comment by pkotvan** [comment]
Thanks folks, this is much appreciated.

**Pull request merged**
