### PR TITLE
Limit size of error_reason

### PR DESCRIPTION
**Pull request by hluk**
Fixes issue with stuck request to ResultsDB.

TODO:
- Why the request did not timeout?
- Limit size of characters in for other fields in POST request.

JIRA: FACTORY-5775
Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by hluk** [comment]
@lcarva  @gnaponie  This is the hot-fix on server.

**Comment by lcarva** [comment]
We should update the message spec to indicate the error message gets truncated.

**Comment by mikebonnet** [comment]
I don't love just dropping potentially useful data. Could we change the data model to increase the size of the field in the database? `TEXT` fields have no arbitrary size limit.

**Comment by hluk** [comment]
I'm failing to reproduce the issue locally in a container -- the environments differ thought -- the postgres patch version is different and I'm using slightly modified `postgresql.conf` from prod.

Here is the original SQL error from resultsdb API server:

```
[Wed Jan 15 13:47:27.316435 2020] [:error] [pid 14187] OperationalError: (OperationalError) index row size 7584 exceeds maximum 2712 for index "result_data_idx_key_value"
[Wed Jan 15 13:47:27.316441 2020] [:error] [pid 14187] HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
[Wed Jan 15 13:47:27.316446 2020] [:error] [pid 14187] Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by hluk** [comment]
Ah, I probably cannot reproduce this because using Python 3 newer versions of alembic and sqlalchemy.

**Comment by hluk** [comment]
OK, so setting a much larger data locally causes the error:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) index row size 2896 exceeds maximum 2712 for index "result_data_idx_key_value"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

...and error in DB pod:

```
index row requires 114504 bytes, maximum size is 8191
```

---

Here are the relevant section from SQL schema:

```sql
CREATE TABLE result_data (
    id integer NOT NULL,
    result_id integer,
    key text,
    value text
);

CREATE INDEX result_data_idx_key_value ON result_data USING btree (key text_pattern_ops, value text_pattern_ops);
```

I guess the `result_data_idx_key_value` index need to be changed so it can handle large values.

**Comment by hluk** [comment]
Unless it's not difficult to fix the index to handle large values, the easy and quick solution is to limit size of all the text values in `result_data`.

**Comment by gnaponie** [comment]
We can increase the size, but at some point, we should set a limit and truncate the data in my opinion... we can't keep increasing the size. But yes, as Lui said, if we truncate the value, we should let the user know that.

**Comment by hluk** [comment]
> We can increase the size

This is some limitation for **DB index** that allows text operations (e.g. `... WHERE item LIKE 'koschei%fc24%'`), not size of a text column.

One solution would be to change the index type to use hashes for the text columns which would mean that it would be no longer possible to check if the values contain a text fragment (it would be possible only to check equality). This would break API (e.g. from docs `item:like=koschei*fc24*`).

**Comment by hluk** [comment]
We should probably merge this now and fix properly later. What do you think?

**Comment by mikebonnet** [comment]
> We should probably merge this now and fix properly later. What do you think?

That sounds reasonable.

**Comment by gnaponie** [comment]
Agreed!

**Pull request merged**
